/**
 * 
 */
var createHTag=x=>{
    return '<h'+x.num+'>'+x.val+'</h'+x.num+'>';
}
var createDiv=x=>{
	return '<div id="'+x.id+'" class="'+x.clazz+'"></div>'
}
var createATag=x=>{
	return '<a id="'+x.id+'" class="'+x.clazz+'" href="#">'+x.txt+'</a>'
}
var createSpan=x=>{
	return '<span id="'+x.id+'" class="'+x.clazz+'"></span>'
}
var doo=x=>{
	return '<div class="bookk-store">'
	+'    <div class="category-wrap">'
	+'        <div class="container">'
	+'            <div class="store-gnb">'
	+'                <ul>'
	+'                    <li class="all-menu">'
	+'                        <a href="#"><span class="ic-list"></span>전체분야<span class="caret"></span></a>'
	+'                        <div class="store-lnb">'
	+'                            <ul>'
	+'                                                                                                    <li class="active">'
	+'                                    <a href="/store/category/1">시·에세이<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/9">시집</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/10">에세이</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/11">기타도서</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/2">소설<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/12">일반</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/13">로맨스</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/14">판타지</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/38">BL</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/39">무협</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/40">추리/스릴러/미스터리</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/41">기타</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/51">SF소설</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/3">전기/회고록<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/15">자서전</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/16">기타</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/4">경영/경제/자기계발<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/18">경영</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/19">경제</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/20">기타</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/5">인문사회<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/21">인문</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/22">정치/사회</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/23">역사</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/42">종교</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/43">예술/문화/기타</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/50">SF 장르</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/26">기타<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/27">과학/IT</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/28">어린이/청소년</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/44">진학,진로</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/45">여행</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/46">가정/생활</a>'
	+'                                        </li>'
	+'                                                                                <li>'
	+'                                            <a href="/store/category/52">교재/참고서</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                                                                    <li class="">'
	+'                                    <a href="/store/category/37">무료체험판<span class="caret right"></span></a>'
	+'                                    <ul>'
	+'                                                                                                                    <li>'
	+'                                            <a href="/store/category/48">전자책</a>'
	+'                                        </li>'
	+'                                                                                                                </ul>'
	+'                                </li>'
	+'                                                            </ul>'
	+'                        </div>'
	+'                    </li>'
	+'                                                                <li><a href="/store/category/1">시·에세이</a></li>'
	+'                                                                <li><a href="/store/category/2">소설</a></li>'
	+'                                                                <li><a href="/store/category/3">전기/회고록</a></li>'
	+'                                                                <li><a href="/store/category/4">경영/경제/자기계발</a></li>'
	+'                                                                <li><a href="/store/category/5">인문사회</a></li>'
	+'                                                                <li><a href="/store/category/26">기타</a></li>'
	+'                                                            </ul>'
	+'            </div>'
	+'        </div>'
	+'    </div>'
	+'    </div>'
}